site_name: DOSAR Outreach Materials
site_url: https://osg-htc.org/dosar
repo_url: https://github.com/osg-htc/dosar
theme: readthedocs

nav:
- Home: 'index.md'
- Current or Upcoming Events:
  - 'ASP 2024 Schedule': 'ASP2024/ASP2024_Schedule.md'
  - 'ASP 2024 Materials': 'ASP2024/ASP2024_Materials.md'
- Past Events:
  - 'ASP 2022 Schedule': 'ASP2022/ASP2022_Schedule.md'
  - 'ASP 2022 Materials': 'ASP2022/ASP2022_Materials.md'
  - 'Data Trieste 2019 Schedule': 'DataTrieste2019/School.md'
  - 'Data Trieste 2019 Materials': 'DataTrieste2019/Materials.md'
  - 'Data Sao Paulo 2018 Schedule': 'DataSaoPaulo2018/School.md'
  - 'Data Sao Paulo 2018 Materials': 'DataSaoPaulo2018/Materials.md'
  - 'Data Kigali 2018 Schedule': 'DataKigali2018/School.md'
  - 'Data Kigali 2018 Materials': 'DataKigali2018/Materials.md'
  - 'Data Trieste 2018 Schedule': 'DataTrieste2018/School.md'
  - 'Data Trieste 2018 Materials': 'DataTrieste2018/Materials.md'
  - 'ASP 2018 Schedule': 'ASP2018/ASP2018_Schedule.md'
  - 'ASP 2018 Material': 'ASP2018/ASP2018_Materials.md'
  - 'Data Sao Paulo Schedule': 'Materials/DSP_DT2017.md'
  - 'Data Sao Paulo Materials': 'Materials/DSP_Materials.md'
  - 'Polar Hackathon Schedule': 'Materials/PH_DT2017.md'
  - 'Polar Hackathon Materials': 'Materials/PH_Materials.md'
- DOSAR Video Meetings:
  - 'October 24, 2018': 'Meetings/24October2018.md'
  - 'March 12, 2019': 'Meetings/12March2019.md'


markdown_extensions:
  - admonition
